package task;

import manager.InMemoryTaskManager;
import manager.Managers;
import manager.TaskManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class InMemoryTaskManagerTest {
    private TaskManager taskManager;

    @BeforeEach
    void setUp() {
        taskManager = Managers.getDefault();
    }

    @Test
    void managerShouldAddAndFindTasks() {
        Task task = new Task("Task", "Description", 1);
        Epic epic = new Epic("Epic", "Description", 2);
        Subtask subtask = new Subtask("Subtask", "Description", 3, Status.NEW, 2);

        taskManager.addTask(task);
        taskManager.addEpic(epic);
        taskManager.addSubtask(subtask);

        assertAll(
                () -> assertEquals(task, taskManager.getById(1)),
                () -> assertEquals(epic, taskManager.getById(2)),
                () -> assertEquals(subtask, taskManager.getById(3))
        );
    }

    @Test
    void manualAndAutoGeneratedIdsShouldNotConflict() {
        Task manualTask = new Task("Manual", "Desc", 100);
        taskManager.addTask(manualTask);
        taskManager.addTask(new Task("Auto", "Desc", 101));

        assertEquals(100, manualTask.getId());
        assertEquals(101, taskManager.getById(101).getId());
    }

    @Test
    void taskShouldBeCopiedWhenAdded() {
        Task original = new Task("Original", "Desc", 10);
        original.setStatus(Status.IN_PROGRESS);

        taskManager.addTask(original);
        original.setTitle("Modified");
        original.setStatus(Status.DONE);

        Task saved = taskManager.getById(10);
        assertAll(
                () -> assertEquals("Original", saved.getTitle()),
                () -> assertEquals(Status.IN_PROGRESS, saved.getStatus())
        );
    }

    @Test
    void shouldNotModifyInternalTaskState() {
        Task task = new Task("Test", "Desc", 1);
        taskManager.addTask(task);

        task.setTitle("Hacked");
        Task saved = taskManager.getById(1);

        assertNotEquals("Hacked", saved.getTitle());
    }
}
